# Generated by Django 3.0.6 on 2020-05-22 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_name', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Script',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_author', models.CharField(max_length=16, verbose_name='脚本作者')),
                ('s_file_name', models.CharField(max_length=100, verbose_name='脚本名称')),
                ('s_file', models.FileField(upload_to='upload/JmeterScript')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=16)),
                ('s_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Grade')),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_file_name', models.CharField(max_length=100)),
                ('d_file', models.FileField(upload_to='upload/JmeterData')),
                ('d_script', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.Script')),
            ],
        ),
    ]
