# Generated by Django 3.0.6 on 2020-05-28 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('caption', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'user_type',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=32)),
                ('email', models.EmailField(max_length=32)),
                ('pwd', models.CharField(max_length=32)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type_user', to='App.UserType')),
            ],
            options={
                'db_table': 'user_info',
            },
        ),
    ]
