# Generated by Django 3.0.6 on 2020-05-22 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_game'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Game',
        ),
    ]
