# Generated by Django 3.0.6 on 2020-05-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_delete_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='d_file',
            field=models.FileField(upload_to='upload/JmeterData'),
        ),
        migrations.AlterField(
            model_name='script',
            name='s_file',
            field=models.FileField(upload_to='upload/JmeterScript'),
        ),
    ]
