# Generated by Django 3.0.6 on 2020-05-21 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JmeterPlatform', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='script',
            old_name='u_file',
            new_name='s_file',
        ),
        migrations.RenameField(
            model_name='script',
            old_name='u_file_name',
            new_name='s_file_name',
        ),
        migrations.RenameField(
            model_name='script',
            old_name='u_name',
            new_name='s_name',
        ),
    ]
