# Generated by Django 3.0.6 on 2020-06-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JmeterPlatform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='script',
            name='deleted',
            field=models.BooleanField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='script',
            name='update_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(verbose_name='运行状态0'),
        ),
    ]
