# Generated by Django 3.0.6 on 2020-05-21 14:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('JmeterPlatform', '0002_auto_20200521_2150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='script',
            old_name='s_name',
            new_name='s_author',
        ),
        migrations.AddField(
            model_name='script',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
