# Generated by Django 2.1.4 on 2020-08-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JmeterPlatform', '0002_auto_20200608_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='s_file',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='脚本路径'),
        ),
    ]
