# Generated by Django 3.0.6 on 2020-05-21 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JmeterPlatform', '0003_auto_20200521_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='s_author',
            field=models.CharField(max_length=16, verbose_name='脚本作者'),
        ),
        migrations.AlterField(
            model_name='script',
            name='s_file',
            field=models.FileField(upload_to='', verbose_name='脚本路径'),
        ),
        migrations.AlterField(
            model_name='script',
            name='s_file_name',
            field=models.CharField(max_length=100, verbose_name='脚本名称'),
        ),
    ]
