# Generated by Django 2.1.4 on 2020-08-12 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JmeterPlatform', '0003_auto_20200811_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False, verbose_name='person_id')),
                ('name', models.CharField(max_length=16, verbose_name='姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
            ],
            options={
                'db_table': 'person',
            },
        ),
        migrations.CreateModel(
            name='PersonInfo',
            fields=[
                ('info_id', models.AutoField(primary_key=True, serialize=False, verbose_name='info_id')),
                ('sex', models.BooleanField(default=0)),
                ('birth', models.DateField()),
                ('tel', models.CharField(max_length=11)),
                ('person', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='JmeterPlatform.Person')),
            ],
            options={
                'db_table': 'person_info',
            },
        ),
    ]
