# Generated by Django 2.1.4 on 2020-08-12 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JmeterPlatform', '0004_person_personinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_id', models.AutoField(primary_key=True, serialize=False, verbose_name='author_id')),
                ('name', models.CharField(max_length=16, verbose_name='姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
            ],
            options={
                'db_table': 'author',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.AutoField(primary_key=True, serialize=False, verbose_name='book_id')),
                ('book_name', models.CharField(max_length=16, verbose_name='书名')),
                ('page', models.IntegerField(verbose_name='页数')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book', to='JmeterPlatform.Author')),
            ],
            options={
                'db_table': 'book',
            },
        ),
        migrations.AlterField(
            model_name='personinfo',
            name='person',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='info', to='JmeterPlatform.Person'),
        ),
    ]
