# Generated by Django 3.0.6 on 2020-05-22 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JmeterPlatform', '0004_auto_20200521_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='d_file',
            field=models.FileField(upload_to='upload/JmeterData/<django.db.models.query_utils.DeferredAttribute object at 0x0000000003DE2D30>'),
        ),
        migrations.AlterField(
            model_name='script',
            name='s_file',
            field=models.FileField(upload_to='upload/JmeterScript/', verbose_name='脚本路径'),
        ),
    ]
