# Generated by Django 2.1.4 on 2020-08-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JmeterPlatform', '0005_auto_20200812_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
            ],
            options={
                'db_table': 'child',
            },
        ),
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colors', models.CharField(max_length=10, verbose_name='颜色')),
            ],
            options={
                'db_table': 'color',
            },
        ),
        migrations.AddField(
            model_name='child',
            name='favor',
            field=models.ManyToManyField(to='JmeterPlatform.Colors'),
        ),
    ]
