# Generated by Django 3.0.6 on 2020-05-22 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JmeterPlatform', '0006_auto_20200522_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='d_file',
            field=models.FileField(upload_to='upload/JmeterData/<django.db.models.query_utils.DeferredAttribute object at 0x0000000003DD4D60>'),
        ),
    ]
