# Generated by Django 3.0.6 on 2020-05-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JmeterPlatform', '0007_auto_20200522_1931'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='script',
            options={'ordering': ['create_time']},
        ),
        migrations.AlterField(
            model_name='data',
            name='d_file',
            field=models.FileField(upload_to='upload/JmeterData/<django.db.models.query_utils.DeferredAttribute object at 0x0000000003DE3DC0>'),
        ),
        migrations.AlterModelTable(
            name='script',
            table='script',
        ),
    ]
