# Generated by Django 3.0.6 on 2020-05-23 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JmeterPlatform', '0010_auto_20200522_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='d_file',
            field=models.FileField(upload_to='upload/JmeterData/<django.db.models.query_utils.DeferredAttribute object at 0x000001E3E7A5A630>'),
        ),
    ]
