# Generated by Django 3.0.6 on 2020-05-23 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('JmeterPlatform', '0011_auto_20200523_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='d_script_name',
            field=models.ForeignKey(default=111, on_delete=django.db.models.deletion.CASCADE, to='JmeterPlatform.Script', to_field='s_file_name'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='data',
            name='d_file',
            field=models.FileField(upload_to='upload/JmeterData/<django.db.models.fields.CharField>'),
        ),
        migrations.AlterField(
            model_name='data',
            name='d_script',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='d_script', to='JmeterPlatform.Script'),
        ),
        migrations.AlterField(
            model_name='script',
            name='s_file_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='脚本名称'),
        ),
    ]
