# Generated by Django 3.0.6 on 2020-05-23 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JmeterPlatform', '0012_auto_20200523_0203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='d_script_name',
        ),
        migrations.AlterField(
            model_name='data',
            name='d_file',
            field=models.FileField(upload_to='upload/JmeterData/'),
        ),
        migrations.AlterField(
            model_name='script',
            name='s_file_name',
            field=models.CharField(max_length=100, verbose_name='脚本名称'),
        ),
    ]
