# Generated by Django 3.0.6 on 2020-05-23 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JmeterPlatform', '0013_auto_20200523_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='d_file',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='script',
            name='s_file',
            field=models.CharField(max_length=100, verbose_name='脚本路径'),
        ),
    ]
